name: sales_tracker
description: "Sales Tracker Mini-Program - 銷售記錄小助手"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: 2.5.3
  intl: ^0.19.0
  uuid: ^4.3.3
  csv: ^6.0.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
